[package]
name = "voxel-world"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.9"
noise = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
voxel-core = { version = "0.1.0", path = "../voxel-core" }
